### ISSUE TITLE
Path to execute is wrong...

### ISSUE THREAD

**Issue by 9brada6** [SanderRonde/phpstan-vscode#7]
Hi... I tried your plugin because it looks refreshed and I like it would be somewhat maintained....

However after installing, I get this error:

![image](https://user-images.githubusercontent.com/19844284/173504786-aaf1a0b5-ad58-4eee-9c9a-16eadbc1ba66.png)

The path to the file is good, but it seems that it looks for the path inside VSCode folder. I though is because I have vs Code portable, but on installed version is the same...

The only option that I have set is: "phpstan.configFile": "./phpstan.neon". I also tried "phpstan.configFile": "phpstan.neon" and is the same....
I'm on Windows if it matters.

**Comment by SanderRonde** [comment]
Don't worry this project is being maintained :)
I've uploaded a version that should fix the issue (version `1.3.1`). Can you check if it fixed it for you?

**Comment by SanderRonde** [comment]
Should be fixed in https://github.com/SanderRonde/phpstan-vscode/commit/6fe5c4f2545490a7fdce91b4c2baaa31256e1407. Please re-open the issue if that's not the case

**Comment by 9brada6** [comment]
Hi... it doesn't work for me at all now... any error is not displayed... but also no errors in development console... I will check via a debugger and see where is going wrong when I have time...

**Comment by SanderRonde** [comment]
The easiest thing to check is the PHPStan section of the output panel. Can you post those results here?

**Comment by 9brada6** [comment]
```
Checking file w:\avada\wordpress\wp-content\themes\Avada\includes\class-awb-typekit-typography.php
Showing status bar
Spawning PHPStan with the following configuration:  {"binCmd":"w:\\avada\\wordpress\\wp-content\\themes\\Avada\\vendor\\bin\\phpstan","args":["analyse","-c","w:\\avada\\wordpress\\wp-content\\themes\\Avada\\phpstan.neon","--error-format=raw","--no-progress","--no-interaction","--memory-limit=1G","w:\\avada\\wordpress\\wp-content\\themes\\Avada\\includes\\class-awb-typekit-typography.php"]}
Document opened, checking
Skipping Log file
Active editor changed, checking
Skipping Log file
PHPStan process exited succesfully
Hiding status bar, last operation result = Success
File check done for file w:\avada\wordpress\wp-content\themes\Avada\includes\class-awb-typekit-typography.php errors= 
Active editor changed, checking
Checking file w:\avada\wordpress\wp-content\themes\Avada\includes\class-awb-typekit-typography.php
Showing status bar
Document opened, checking
Skipping scminput file
Spawning PHPStan with the following configuration:  {"binCmd":"w:\\avada\\wordpress\\wp-content\\themes\\Avada\\vendor\\bin\\phpstan","args":["analyse","-c","w:\\avada\\wordpress\\wp-content\\themes\\Avada\\phpstan.neon","--error-format=raw","--no-progress","--no-interaction","--memory-limit=1G","w:\\avada\\wordpress\\wp-content\\themes\\Avada\\includes\\class-awb-typekit-typography.php"]}
PHPStan process exited succesfully
Hiding status bar, last operation result = Success
File check done for file w:\avada\wordpress\wp-content\themes\Avada\includes\class-awb-typekit-typography.php errors= 
Document opened, checking
Skipping Log file
Active editor changed, checking
Skipping Log file
```

**Comment by SanderRonde** [comment]
Hmm looks like it's running successfully and just not encountering any errors. What output do you get when you run the command manually on those files?

**Comment by 9brada6** [comment]
When I run manually it works... when I run on another, but smaller project, the errors appear, but do not get highlighted and do not appear in problems tab:

https://user-images.githubusercontent.com/19844284/173919327-df6db1f4-a435-4f4d-9803-faa5ba462057.mp4

**Comment by SanderRonde** [comment]
Ah I've found the error. Should be fixed in a new release (which I'll create soon).

**Comment by 9brada6** [comment]
Checked... but still the same... now the errors inside output looks like this:
`File check done for file w:\fusion-tests\main-platform\Servers\Server.php errors= ["Property FT\\Servers\\Server::$server_configuration is never read, only written.","Method FT\\Servers\\Server::waitForContainerToStop() invoked with 1 parameter, 0 required."]`

I just wonder if for you it works... it is because you have a different OS?

**Comment by SanderRonde** [comment]
Hmm it should be working now (also yeah I did update the error formatting a bit). I'm testing it on windows too so I'm not sure why it's not working. Can you check the dev tools and see if that lists anything? The error was a "failed to read file ...." error so maybe something like that again?

**Comment by 9brada6** [comment]
Yes... I got this: 
![image](https://user-images.githubusercontent.com/19844284/173930000-4bd57178-f182-4523-ad0a-df5828e76f0a.png)

**Comment by SanderRonde** [comment]
Ah so something is going wrong in removing baseline errors. Can you try out this demo build and tell me what it logs? Two things should be added:
* It should now log where it's going wrong
* It should succeed in displaying errors (although filtering stuff from a baseline file might fail)

It's a .zip file because github doesn't allow uploading .vsix files. Just rename it to .vsix and install it.
[phpstan-vscode-1.3.3.zip](https://github.com/SanderRonde/phpstan-vscode/files/8913240/phpstan-vscode-1.3.3.zip)

**Comment by SanderRonde** [comment]
Alright I found the error. Thanks for your help. Fix should be live soon.
